disabled_rules:
- identifier_name
- nesting
- function_parameter_count
- trailing_whitespace
- type_name
- todo
- inert_defer
- syntactic_sugar
- implicit_getter
- non_optional_string_data_conversion

opt_in_rules:
- control_statement
- empty_count
- trailing_newline
- colon
- comma

function_body_length:
- 70 # warning
- 71 #error

file_length:
- 1499 # warning
- 1500 # error

type_body_length:
- 399 # warning
- 400 # error

line_length:
- 270 # warning
- 271 # error

cyclomatic_complexity:
- 11 # warning
- 12 # error

excluded:
- Pods
- Carthage
- .build
